name: Release

on: push

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Check Commit Message
        id: check-commit-message
      # https://stackoverflow.com/questions/58862864/github-actions-ci-conditional-regex#58869470
      # \d to match a digit is supported on macOS, but not on Linux - use [0-9]
        run: |
          if [[ ${{ github.event.head_commit.message }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - name: Checkout
        uses: actions/checkout@v5
        if: steps.check-commit-message.outputs.match == 'true'
      - name: Push Tag
        if: steps.check-commit-message.outputs.match == 'true'
        run: |
          git tag ${{ github.event.head_commit.message }}
          git push origin tag ${{ github.event.head_commit.message }}
        shell: bash
      - name: Build
        if: steps.check-commit-message.outputs.match == 'true'
        run: |
          npm -v
        shell: bash